Chaitanya Deo\
24-27-17\
M.Tech Data Science\
Data Science Tools and Techniques (AM-609)\
Assignment 2

Q.1\
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange\
b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function\
c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.\
d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)\
e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:\
(i) Sum var3 over its second dimension and print the result.\
(ii) Sum var3 over its third dimension and print the result.\
(iii) Sum var3 over both its first and third dimensions and print the result.\
f) Write code to do the following:\
(i) Slice out the second row of var2 and print it.\
(ii) Slice out the last column of var2 using the -1 notation and print it.\
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [1]:
import numpy as np

In [2]:
var1 = np.arange(31) # (a)
print("var1 - ", var1)
print("Shape of var1 - ", var1.shape)

var1 -  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1 -  (31,)


In [3]:
var2 = var1[:-1].reshape(6,5) # (b)
print("var2 - ", var2)
print("Shape of var2 - ", var2.shape)

var2 -  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Shape of var2 -  (6, 5)


In [4]:
var3 = np.reshape(var2, (3,5,2)) # (c)
print("var3 - ", var3)
print("Shape of var3 - ", var3.shape)

var3 -  [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
Shape of var3 -  (3, 5, 2)


In [5]:
var2[1,0] = -1  #(d)
print("var1 - ", var1)
print("var3 - ", var3)

var1 -  [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3 -  [[[ 0  1]
  [ 2  3]
  [ 4 -1]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


Yes var1 and var3 changed. This is because reshape return view of the array, not a new copy. It is same data represented in diffrent way.\
All 3 variables var1, var2 and var3 refer to same data.

In [6]:
# (e)
print("(i) Sum var3 over its second dimension and print the result = ", np.sum(var3, axis=1))
print("(ii) Sum var3 over its third dimension and print the result = ",np.sum(var3, axis=2))
print("(iii) Sum var3 over both its first and third dimensions and print the result = ", np.sum(var3, axis=(0,2)))

(i) Sum var3 over its second dimension and print the result =  [[ 20  19]
 [ 70  75]
 [120 125]]
(ii) Sum var3 over its third dimension and print the result =  [[ 1  5  3 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]]
(iii) Sum var3 over both its first and third dimensions and print the result =  [ 63  75  81  99 111]


In [7]:
#(e)
print("var2 :- \n",var2)
print("\n(i) Slice out the second row of var2 - " , var2[1,:])
print()
print("(ii) Slice out the last column of var2 using the -1 notation - ", var2[:,-1])
print()
print("(iii) Slice out the top right 2 × 2 submatrix of var2 -\n ", var2[:2, -2:])

var2 :- 
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

(i) Slice out the second row of var2 -  [-1  6  7  8  9]

(ii) Slice out the last column of var2 using the -1 notation -  [ 4  9 14 19 24 29]

(iii) Slice out the top right 2 × 2 submatrix of var2 -
  [[3 4]
 [8 9]]


Q.2\
a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.\
b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.\
c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.\
    import numpy.random as npr\
    data = np.exp(npr.randn ( 50 , 5 ))\
d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.\
e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.\
f) Now standardize the data matrix by
1) subtracting the mean off of each column
2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [8]:
vect1 = np.arange(1,11) #(a)
print("Orignal vector = ", vect1)
vect1 = vect1 + 1
print("Result of binary add operation (broadcast with a scalar - ",vect1)

Orignal vector =  [ 1  2  3  4  5  6  7  8  9 10]
Result of binary add operation (broadcast with a scalar -  [ 2  3  4  5  6  7  8  9 10 11]


In [9]:
print("b) 10 x 10 matrix in which Aij = i+j, with previously created vector : \n", vect1.reshape(10,1) + vect1)

b) 10 x 10 matrix in which Aij = i+j, with previously created vector : 
 [[ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]
 [12 13 14 15 16 17 18 19 20 21]
 [13 14 15 16 17 18 19 20 21 22]]


In [10]:
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ))

In [11]:
mean = data.mean(axis=0)
std = data.std(axis=0)
print("Mean - ", mean)
print("Standard Deviation = ", std) 

Mean -  [1.15297923 2.69494424 1.80804087 0.82953148 1.39646923]
Standard Deviation =  [1.23029833 4.96014806 2.17568907 0.82538222 1.23125503]


In [12]:
normalized = (data-mean)/std
print("Normalized data:\n", normalized)

Normalized data:
 [[-6.98791826e-01 -2.28396934e-01 -2.40722830e-01 -6.19550850e-01
  -6.97454931e-01]
 [ 8.62105247e-02  1.68670262e-01 -4.81199414e-01  1.13066966e-01
  -5.57618245e-02]
 [-2.51319658e-01 -2.65476776e-01 -4.58490642e-02 -6.13848629e-01
  -8.30924488e-01]
 [-2.19480104e-01 -3.12459364e-01  5.22094046e+00 -2.09661806e-01
   3.64359111e-01]
 [-1.32536000e-01 -3.44934935e-01 -7.93558840e-01 -2.68525505e-01
  -7.00424037e-01]
 [-4.62181244e-01  1.67604775e-01 -4.88125624e-01 -6.93766419e-01
  -1.02115097e+00]
 [ 4.15968764e+00 -4.37114664e-01 -2.62572690e-01  2.23593108e-01
  -8.95709049e-01]
 [-9.01617069e-01  7.01126471e-01 -6.13527589e-01 -3.27697006e-01
   1.25317687e-01]
 [-7.62959182e-01  5.70617915e-03 -1.71530180e-01  2.93004625e-01
   5.27510659e-01]
 [-1.23553975e-01 -4.14042394e-01  3.10551706e-01 -6.97282804e-01
   2.21410532e+00]
 [ 6.17666057e-01 -2.77003516e-02 -6.92420574e-01 -5.51885562e-01
  -5.74859002e-01]
 [-8.17656825e-01 -2.03889914e-01 -7.71517618e-

In [13]:
print("Normalized mean = ", normalized.mean(axis=0))
print("Normalized Standard deviation = ", normalized.std(axis=0))

print("\n** The mean of normalized data is not exactly zero due to limitation of floating-point arithmetic, but is very close to zero")

Normalized mean =  [ 1.65700786e-16 -9.54791801e-17 -2.57571742e-16 -9.54791801e-17
  2.05391260e-17]
Normalized Standard deviation =  [1. 1. 1. 1. 1.]

** The mean of normalized data is not exactly zero due to limitation of floating-point arithmetic, but is very close to zero


Q.3\
a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector 
${\begin{bmatrix} 
    x_1 \ x_2 \ \cdots \ x_N 
\end{bmatrix}^T}$ ,then the associated (square) Vandermonde matrix would be\
\begin{equation}
V=
\begin{pmatrix}
  1       & x^1_1   & x^2_1   & \cdots  & x^{n-1}_1  \\
  1       & x^1_2   & x^2_2   & \cdots  & x^{n-1}_2  \\
  \vdots  & \vdots  & \vdots  & \ddots  & \vdots \\
  1       & x^1_n   & x^2_n   & \cdots  & x^{n-1}_n  \\
\end{pmatrix}
\end{equation}

Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector 
${\begin{bmatrix} 
    1 \ 2 \ \cdots \ N 
\end{bmatrix}^T}$
for any N. Do it without using a loop. Here’s a stub to get you started:\
&nbsp; &nbsp; &nbsp; def vandermonde (N):\
&nbsp; &nbsp; &nbsp; vec = np.arange (N) +1\
&nbsp; &nbsp; &nbsp; \#write your code here.\
Use your function for N = 12, store it in variable named vander, and print the
result.\
b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.\
c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.\
d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

In [14]:
def vandermonde(n):
    vec = np.arange(n) + 1
    return vec.reshape(n,1)**np.arange(n)

In [15]:
van = vandermonde(12)
print(van) #(a) part

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

In [16]:
x = np.ones(12)
b = van @ x
print(b) #(b) part

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


In [17]:
from numpy import linalg
print(linalg.inv(van) @ b)

[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


The Expected result of matirx multiplication of inverse of vandermonde matrix and b is vector of all onces, since the original 'x' was a vector of all onces. The difference indicates numerical instability due to limitation of floating-point arithmetic.

In [19]:
linalg.solve(van, b)

array([0.98080503, 1.05139768, 0.94513807, 1.03151945, 0.98899166,
       1.00248816, 0.99962407, 1.0000384 , 0.99999737, 1.00000012,
       1.        , 1.        ])

Using linalg.solve gives a more accurate solution which is close to vector of all ones, since is more robust for solving linear system.

<b>Github link to file<b>\
https://github.com/ChaitanyaDeo/DIAT_MTech/blob/main/DSTT/Assn2_ChaitanyaDeo_24-27-17.ipynb